# -*- coding: utf-8 -*-
"""MyFirstColabNotebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w70ykz5mD3hBQEJb90qp_uWQa_ftFYfn
"""

import time
print(time.ctime())

!pip install numpy

from google.colab import drive
drive.mount('/content/drive')

# @title Students form
import ipywidgets as widgets
from IPython.display import display, HTML

# קריאת קובץ הסטודנטים
file_path = '/content/drive/MyDrive/students.txt'

with open(file_path, 'r') as file:
    lines = file.readlines()

# שמירה בלי כפילויות לפי מייל
students_dict = {}

for line in lines:
    line = line.strip()
    if line != "":
        parts = [p.strip() for p in line.split(',')]

        if len(parts) >= 5:
            student = {
                'first_name': parts[0],
                'last_name': parts[1],
                'email': parts[2],
                'courses': parts[3],
                'link': parts[4]
            }
            students_dict[student['email']] = student

students = list(students_dict.values())

# שמות לדרופדאון
student_names = ['בחר/י סטודנט']
for s in students:
    student_names.append(s['first_name'] + " " + s['last_name'])

# מידות
LABEL_WIDTH = '170px'
FIELD_WIDTH = '470px'
BOX_WIDTH = '700px'

# CSS
display(HTML("""
<style>
.widget-text input,
.widget-textarea textarea,
.widget-dropdown select {
    border: 1.8px solid #e7c4d8 !important;
    border-radius: 14px !important;
    background-color: #fffafd !important;
    color: #5a3950 !important;
    font-size: 15px !important;
    padding: 10px 12px !important;
    box-shadow: none !important;
    direction: rtl !important;
    text-align: right !important;
}

.widget-dropdown select {
    appearance: none !important;
    -webkit-appearance: none !important;
    -moz-appearance: none !important;
    background-image: url("data:image/svg+xml;utf8,<svg fill='%23c21875' height='20' viewBox='0 0 24 24' width='20' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/></svg>");
    background-repeat: no-repeat;
    background-position: left 12px center;
    background-size: 16px;
    padding-left: 35px !important;
}

.widget-text input:focus,
.widget-textarea textarea:focus,
.widget-dropdown select:focus {
    border-color: #d56aa1 !important;
    box-shadow: 0 0 0 2px rgba(213,106,161,0.12) !important;
}

.widget-button {
    border-radius: 14px !important;
    font-size: 16px !important;
}

input:disabled,
textarea:disabled {
    opacity: 1 !important;
    -webkit-text-fill-color: #7b6571 !important;
    background-color: #fffafd !important;
}

.jp-RenderedHTMLCommon a {
    color: #c21875 !important;
    text-decoration: none !important;
    font-weight: bold;
}

.jp-RenderedHTMLCommon a:hover {
    text-decoration: underline !important;
}
</style>
"""))

# כותרת ראשית
display(HTML(f"""
<div style="
    background: linear-gradient(135deg, #ffeaf4, #fdf3ff);
    padding: 26px;
    border-radius: 26px;
    border: 2px solid #f1c6dd;
    width: {BOX_WIDTH};
    box-sizing: border-box;
    box-shadow: 0 8px 22px rgba(0,0,0,0.07);
    margin-bottom: 18px;
">
    <h2 style="
        color: #c40071;
        text-align: center;
        margin: 0;
        font-family: Arial;
        font-size: 25px;
        letter-spacing: 0.3px;
    ">
        טופס סטודנטים
    </h2>
    <p style="
        text-align: center;
        color: #8a5d77;
        font-size: 15px;
        margin-top: 12px;
        margin-bottom: 0;
        font-family: Arial;
    ">
        בחר/י סטודנט ולאחר מכן יוצגו כל הפרטים בצורה נעימה ומסודרת
    </p>
</div>
"""))

# layouts
field_layout = widgets.Layout(width=FIELD_WIDTH, height='44px')
textarea_layout = widgets.Layout(width=FIELD_WIDTH, height='95px')
button_layout = widgets.Layout(width='200px', height='46px')

# שדות
dropdown = widgets.Dropdown(
    options=student_names,
    value='בחר/י סטודנט',
    layout=field_layout
)

txt_first_name = widgets.Text(
    value='',
    placeholder='שם פרטי',
    layout=field_layout,
    disabled=True
)

txt_last_name = widgets.Text(
    value='',
    placeholder='שם משפחה',
    layout=field_layout,
    disabled=True
)

txt_email = widgets.Text(
    value='',
    placeholder='כתובת מייל',
    layout=field_layout,
    disabled=True
)

txt_courses = widgets.Textarea(
    value='',
    placeholder='קורסים',
    layout=textarea_layout,
    disabled=True
)

txt_link = widgets.Text(
    value='',
    placeholder='קישור',
    layout=field_layout,
    disabled=True
)

txt_favorite = widgets.Text(
    value='',
    placeholder='הכניס/י תוכנית אהובה...',
    layout=field_layout
)

# אזור לקישור לחיץ
link_output = widgets.Output()

# פונקציה ליצירת תווית
def make_label(icon, text, height='44px', top_padding='0px'):
    return widgets.HTML(
        value=f"""
        <div style="
            width: {LABEL_WIDTH};
            height: {height};
            display: flex;
            justify-content: flex-start;
            align-items: {'flex-start' if height != '44px' else 'center'};
            padding-top: {top_padding};
            padding-right: 0px;
            box-sizing: border-box;
            direction: rtl;
            text-align: right;
            color: #7a3357;
            font-weight: bold;
            font-size: 16px;
            font-family: Arial;
            gap: 6px;
        ">
            <span>{icon}</span>
            <span>{text}:</span>
        </div>
        """,
        layout=widgets.Layout(width=LABEL_WIDTH, height=height)
    )

# פונקציה ליצירת שורה
def make_row(label_widget, field_widget, margin='8px 0'):
    return widgets.HBox(
        [label_widget, field_widget],
        layout=widgets.Layout(
            width='100%',
            display='flex',
            flex_flow='row-reverse',
            justify_content='flex-start',
            align_items='center',
            margin=margin,
            padding='0'
        )
    )
# תוויות
label_student = make_label("🎓", "סטודנט")
label_first_name = make_label("👤", "שם")
label_last_name = make_label("🪪", "משפחה")
label_email = make_label("📧", "מייל")
label_courses = make_label("📚", "קורסים", height='95px', top_padding='10px')
label_link = make_label("🔗", "קישור")
label_favorite = make_label("💖", "תוכנית אהובה")

# שורות
row_student = make_row(label_student, dropdown)
row_first_name = make_row(label_first_name, txt_first_name)
row_last_name = make_row(label_last_name, txt_last_name)
row_email = make_row(label_email, txt_email)
row_courses = make_row(label_courses, txt_courses, margin='8px 0 2px 0')
row_link = make_row(label_link, txt_link)
row_favorite = make_row(label_favorite, txt_favorite)

# כותרות פנימיות
choose_title = widgets.HTML("""
<div style="
    color:#c21875;
    font-weight:bold;
    font-size:19px;
    margin-bottom:6px;
    font-family:Arial;
    text-align:right;
    direction: rtl;
">
    בחירת סטודנט
</div>
""")

details_title = widgets.HTML("""
<div style="
    color:#c21875;
    font-weight:bold;
    font-size:19px;
    margin-bottom:6px;
    font-family:Arial;
    text-align:right;
    direction: rtl;
">
    פרטי הסטודנט
</div>
""")

# כפתור
button = widgets.Button(
    description='עדכון',
    layout=button_layout
)
button.style.button_color = '#efb0d3'
button.style.font_weight = 'bold'

button_box = widgets.HBox(
    [button],
    layout=widgets.Layout(
        justify_content='center',
        width='100%',
        margin='16px 0 0 0'
    )
)

output = widgets.Output()

# קופסת בחירה
top_box = widgets.VBox(
    [
        choose_title,
        row_student
    ],
    layout=widgets.Layout(
        border='2px solid #f1c6dd',
        border_radius='24px',
        padding='22px 24px',
        width=BOX_WIDTH,
        box_sizing='border-box',
        background_color='#fffafd',
        box_shadow='0 5px 14px rgba(0,0,0,0.05)',
        margin='0 0 16px 0'
    )
)

# קופסת פרטים
details_box = widgets.VBox(
    [
        details_title,
        row_first_name,
        row_last_name,
        row_email,
        row_courses,
        row_link,
        link_output,
        row_favorite,
        button_box,
        output
    ],
    layout=widgets.Layout(
        display='none',
        border='2px solid #f1c6dd',
        border_radius='24px',
        padding='22px 24px',
        width=BOX_WIDTH,
        box_sizing='border-box',
        background_color='#fffafd',
        box_shadow='0 5px 14px rgba(0,0,0,0.05)'
    )
)

# הצגת קישור לחיץ
def show_clickable_link(link):
    with link_output:
        link_output.clear_output()

        clean_link = link.strip()
        if clean_link == "":
            return

        href = clean_link
        if not (href.startswith("http://") or href.startswith("https://")):
            href = "https://" + href

        display(HTML(f"""
        <div style="
            direction: rtl;
            text-align: right;
            margin-top: -2px;
            margin-bottom: 8px;
            font-family: Arial;
            padding-right: 180px;
        ">
            <a href="{href}" target="_blank">
                לפתיחת הקישור לחצי כאן
            </a>
        </div>
        """))

# בעת בחירת סטודנט
def on_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        selected_name = change['new']

        if selected_name == 'בחר/י סטודנט':
            details_box.layout.display = 'none'
            txt_first_name.value = ''
            txt_last_name.value = ''
            txt_email.value = ''
            txt_courses.value = ''
            txt_link.value = ''
            txt_favorite.value = ''
            output.clear_output()
            link_output.clear_output()
            return

        for s in students:
            full_name = s['first_name'] + " " + s['last_name']
            if full_name == selected_name:
                txt_first_name.value = s['first_name']
                txt_last_name.value = s['last_name']
                txt_email.value = s['email']
                txt_courses.value = s['courses']
                txt_link.value = s['link']
                txt_favorite.value = ''
                output.clear_output()
                show_clickable_link(s['link'])
                details_box.layout.display = 'flex'
                break

dropdown.observe(on_change)

# שמירה
def on_button_clicked(b):
    with output:
        output.clear_output()

        favorite_value = txt_favorite.value.strip()

        if favorite_value == "":
            display(HTML("""
            <div style="
                color:#b0004f;
                font-weight:bold;
                text-align:center;
                font-size:16px;
                margin-top:10px;
                font-family:Arial;
                background:#ffe6ef;
                border:1px solid #f1a8c8;
                border-radius:14px;
                padding:10px;
            ">
                *יש להזין תוכנית אהובה לפני השמירה*
            </div>
            """))
            return

        new_line = (
            txt_first_name.value + " , " +
            txt_last_name.value + " , " +
            txt_email.value + " , " +
            txt_courses.value + " , " +
            txt_link.value + " , " +
            favorite_value + "\n"
        )

        with open(file_path, 'a', encoding='utf-8') as file:
            file.write(new_line)

        display(HTML("""
        <div style="
            color:#c21875;
            font-weight:bold;
            text-align:center;
            font-size:16px;
            margin-top:10px;
            font-family:Arial;
            background:#fff0f7;
            border:1px solid #f1c6dd;
            border-radius:14px;
            padding:10px;
        ">
            ✨ נשמר בהצלחה
        </div>
        """))

button.on_click(on_button_clicked)

# הצגה
display(top_box)
display(details_box)