# -*- coding: utf-8 -*-
"""tirgul5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJLdFnNt0lyoSVdYwkXw5ltS0AsbolNY
"""

import ipywidgets as widgets
from IPython.display import display, HTML
import matplotlib.pyplot as plt
import requests
import pandas as pd

url = 'https://data.gov.il/api/3/action/datastore_search?resource_id=053cea08-09bc-40ec-8f7a-156f0677aff3'

pd.set_option("display.max_columns", None)

response = requests.get(url)
data = response.json()

data_df = pd.DataFrame(data['result']['records'])
data_df.head()

tab1_content = widgets.Output()

with tab1_content:
    print("Statistics of all data: ")
    display(data_df.describe(include='all'))

tab2_content = widgets.Output()

with tab2_content:
    print("All data: ")
    display(HTML(data_df.head(20).to_html()))

tab3_content = widgets.Output()

with tab3_content:
    print("Number of cars by year of manufacture: ")

    cars_per_year = data_df['shnat_yitzur'].value_counts().sort_index()

    plt.figure(figsize=(12, 6))
    plt.bar(cars_per_year.index, cars_per_year.values)
    plt.xlabel("Year of manufacture")
    plt.ylabel("Number of cars")
    plt.title("The number of different cars produced each year")
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.show()

tabs = widgets.Tab(children=[tab1_content, tab2_content, tab3_content])

tabs.set_title(0, 'Statistics')
tabs.set_title(1, 'All data')
tabs.set_title(2, 'Graph by year')

display(tabs)