# -*- coding: utf-8 -*-
"""Copy of tut5FirebaseHTMLwidgets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvfH_hialGRP3vhAl6EIId1BaFXIm3or
"""

!pip install firebase

"""Solution for tirgul 3"""

from firebase import firebase
import re

# Initialize Firebase connection
FBconn = firebase.FirebaseApplication(
    'https://targul3-default-rtdb.firebaseio.com/', None
)

BASE_PATH = '/wordsCounter/'


def get_all_words():
    """Retrieve all saved words"""
    return FBconn.get(BASE_PATH, None)


def find_word_record(word):
    """Find a word in Firebase and return (record_id, data) if exists"""
    records = get_all_words()
    if records:
        for record_id, data in records.items():
            if data.get('word', '').lower() == word.lower():
                return record_id, data
    return None, None


def add_single_word(word):
    """Add one word or increase its count if it already exists"""
    record_id, data = find_word_record(word)

    if record_id:
        current_count = data.get('count', 0)
        FBconn.put(BASE_PATH + record_id, 'count', current_count + 1)
        print(f'"{word}" already exists. Count updated to {current_count + 1}')
    else:
        new_data = {
            'word': word.lower(),
            'count': 1
        }
        result = FBconn.post(BASE_PATH, new_data)
        print(f'Word "{word}" added successfully! Record ID: {result["name"]}')


def add_text_for_analysis(text):
    """Split text into words and count appearances"""
    words = re.findall(r'\b\w+\b', text.lower())

    if not words:
        print("No valid words found in the text.")
        return

    for word in words:
        add_single_word(word)

    print("Text analysis completed successfully!")


def update_word_count(word, new_count):
    """Update count of an existing word"""
    record_id, data = find_word_record(word)

    if record_id:
        FBconn.put(BASE_PATH + record_id, 'count', new_count)
        print(f'Count for "{word}" updated to {new_count}')
    else:
        print(f'Word "{word}" does not exist.')


def delete_word(word):
    """Delete a word from Firebase"""
    record_id, data = find_word_record(word)

    if record_id:
        FBconn.delete(BASE_PATH, record_id)
        print(f'Word "{word}" deleted successfully!')
    else:
        print(f'Word "{word}" not found.')


def display_all_words():
    """Display all saved words"""
    records = get_all_words()

    if records:
        print("\nAll saved words:")
        for record_id, data in records.items():
            print(f'{data["word"]}: {data["count"]}')
    else:
        print("\nNo words found.")


while True:
    print("\nWords Counter Menu:")
    print("1. Add single word")
    print("2. Add text for analysis")
    print("3. Update word count")
    print("4. Delete word")
    print("5. View all words")
    print("6. Exit")

    choice = input("\nSelect an option (1-6): ")

    if choice == '1':
        word = input("Enter a single word: ").strip()
        if word:
            add_single_word(word)
        else:
            print("Please enter a valid word.")

    elif choice == '2':
        text = input("Enter text for analysis: ").strip()
        if text:
            add_text_for_analysis(text)
        else:
            print("Please enter some text.")

    elif choice == '3':
        word = input("Enter the word to update: ").strip()
        if not word:
            print("Please enter a valid word.")
            continue

        try:
            new_count = int(input("Enter the new count: "))
            if new_count < 0:
                print("Count cannot be negative.")
            else:
                update_word_count(word, new_count)
        except ValueError:
            print("Please enter a valid number.")

    elif choice == '4':
        word = input("Enter the word to delete: ").strip()
        if word:
            delete_word(word)
        else:
            print("Please enter a valid word.")

    elif choice == '5':
        display_all_words()

    elif choice == '6':
        print("Exiting program...")
        break

    else:
        print("Invalid choice. Please try again.")

from firebase import firebase
FBconn = firebase.FirebaseApplication('https://targul3-default-rtdb.firebaseio.com/',None)
while True:
  temperature = int (input ("what is the temperature?"))
  data_to_upload = {
      'Temp' : temperature
  }
  result = FBconn.post('/myTest1/',data_to_upload)
  print(result)

from firebase import firebase

firebase = firebase.FirebaseApplication('https://spring2026-fa74f-default-rtdb.firebaseio.com/', None)
result = firebase.get('/myTest1/', None)
print(result)

import json
from firebase import firebase
FBconn = firebase.FirebaseApplication('https://spring2026-fa74f-default-rtdb.firebaseio.com/',None)
res=FBconn.get('/myTest1/',None)

for key in res:
    print(key+":\t", res[key])

from firebase import firebase
import time

# Initialize Firebase connection
FBconn = firebase.FirebaseApplication('https://spring2026-fa74f-default-rtdb.firebaseio.com/', None)

def get_all_records():
    """Retrieve all temperature records"""
    return FBconn.get('/myTest1/', None)

def update_temperature(record_id, new_temp):
    """Update an existing temperature record"""
    return FBconn.put('/myTest1/' + record_id, 'Temp', new_temp)

def delete_record(record_id):
    """Delete a temperature record"""
    return FBconn.delete('/myTest1/', record_id)

def display_records():
    """Display all temperature records"""
    records = get_all_records()
    if records:
        print("\nCurrent Records:")
        for record_id, data in records.items():
            print(f"ID: {record_id} - Temperature: {data['Temp']}°C")
    else:
        print("\nNo records found")

while True:
    print("\nTemperature Tracker Menu:")
    print("1. Add new temperature")
    print("2. Update existing temperature")
    print("3. Delete temperature record")
    print("4. View all records")
    print("5. Exit")

    choice = input("\nEnter your choice (1-5): ")

    if choice == '1':
        # Add new temperature
        try:
            temperature = int(input("What is the temperature? "))
            data_to_upload = {
                'Temp': temperature,
                'timestamp': time.time()  # Adding timestamp for better tracking
            }
            result = FBconn.post('/myTest1/', data_to_upload)
            print(f"Temperature added successfully! Record ID: {result['name']}")
        except ValueError:
            print("Please enter a valid number for temperature")

    elif choice == '2':
        # Update existing temperature
        display_records()
        record_id = input("\nEnter the record ID to update: ")
        try:
            new_temp = int(input("Enter the new temperature: "))
            result = update_temperature(record_id, new_temp)
            if result:
                print("Temperature updated successfully!")
            else:
                print("Failed to update temperature. Check if the ID exists.")
        except ValueError:
            print("Please enter a valid number for temperature")

    elif choice == '3':
        # Delete temperature record
        display_records()
        record_id = input("\nEnter the record ID to delete: ")
        result = delete_record(record_id)
        if result is None:
            print("Record deleted successfully!")
        else:
            print("Failed to delete record. Check if the ID exists.")

    elif choice == '4':
        # View all records
        display_records()

    elif choice == '5':
        print("Exiting program...")
        break

    else:
        print("Invalid choice. Please try again.")

from IPython.display import HTML
from google.colab.output import _publish as publish
publish.css("b {color: blue}")
HTML("Now <b>bold</b> and <b>blue</b> too.")

import IPython

html_code = \
'''
<p>Now this is <i>really</i> awesome!</p>
<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/768px-Python.svg.png'></img>
'''


display(IPython.display.HTML(html_code))

import altair as alt
import ipywidgets as widgets
from vega_datasets import data

source = data.stocks()

stock_picker = widgets.SelectMultiple(
    options=source.symbol.unique(),
    value=list(source.symbol.unique()),
    description='Symbols')

# The value of symbols will come from the stock_picker.
@widgets.interact(symbols=stock_picker)
def render(symbols):
  selected = source[source.symbol.isin(list(symbols))]

  return alt.Chart(selected).mark_line().encode(
      x='date',
      y='price',
      color='symbol',
      strokeDash='symbol',
  )

from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      // Resize the output to fit the video element.
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

from IPython.display import Image
try:
  filename = take_photo()
  print('Saved to {}'.format(filename))

  # Show the image which was just taken.
  display(Image(filename))
except Exception as err:
  # Errors will be thrown if the user does not have a webcam or if they do not
  # grant the page permission to access it.
  print(str(err))

import IPython
js_code = '''
document.querySelector("#output-area").appendChild(document.createTextNode("hello world!"));
'''
display(IPython.display.Javascript(js_code))

import IPython
from google.colab import output

display(IPython.display.HTML('''
    The items:
    <br><ol id="items"></ol>
    <button id='button'>Click to add</button>
    <script>
      document.querySelector('#button').onclick = () => {
        google.colab.kernel.invokeFunction('notebook.AddListItem', [], {});
      };
    </script>
    '''))

def add_list_item():
  # Use redirect_to_element to direct the elements which are being written.
  with output.redirect_to_element('#items'):
    # Use display to add items which will be persisted on notebook reload.
    display(IPython.display.HTML('<li> Another item</li>'))

output.register_callback('notebook.AddListItem', add_list_item)

import IPython
import uuid
from google.colab import output

class InvokeButton(object):
  def __init__(self, title, callback):
    self._title = title
    self._callback = callback

  def _repr_html_(self):
    callback_id = 'button-' + str(uuid.uuid4())
    output.register_callback(callback_id, self._callback)

    template = """<button id="{callback_id}">{title}</button>
        <script>
          document.querySelector("#{callback_id}").onclick = (e) => {{
            google.colab.kernel.invokeFunction('{callback_id}', [], {{}})
            e.preventDefault();
          }};
        </script>"""
    html = template.format(title=self._title, callback_id=callback_id)
    return html

def do_something():
  print('here')

InvokeButton('click me', do_something)

import ipywidgets as widgets

slider = widgets.IntSlider(20, min=0, max=100)
slider