# -*- coding: utf-8 -*-
"""Copy of BigDataPySpark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w2C__ITG6Dcxmbg1rh35dmrv2KFLxpI8

# **Step 1 - Installation**
"""

# Install Java
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

# Download the latest Apache Spark version
!wget -q https://archive.apache.org/dist/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz
!tar xf spark-3.4.1-bin-hadoop3.tgz

# Install findspark to connect Python with Spark
!pip install -q findspark

"""# **Step 2 - Environment Setup**"""

# Import the os module to interact with the operating system
import os
# Import findspark to locate the Spark installation
import findspark

# Set the environment variable for Java home directory (required for Spark to run)
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
# Set the environment variable for Spark home directory to the downloaded Spark path
os.environ["SPARK_HOME"] = "/content/spark-3.4.1-bin-hadoop3"

# Initialize findspark to make pyspark importable within Python
findspark.init()

"""# **Step 3 - Create SparkSession**"""

# Import SparkSession class from PySpark SQL module
from pyspark.sql import SparkSession

# Create a SparkSession object, which is the entry point to use Spark functionality
  # Set the name of the Spark application to be "Big Data Example"
  # Create a new SparkSession or return an existing one
spark = SparkSession.builder.appName("Big Data Example").getOrCreate()

from google.colab import drive
drive.mount('/content/drive')

"""Read measurements CSV"""

import pandas as pd
import json

df = pd.read_csv(
    "/content/drive/MyDrive/نسخة من csv_json-20251229-2143.csv"
)

measurements = df["value"].apply(json.loads)

data = pd.DataFrame(
    measurements.tolist()
)

data.head()

rdd = spark.sparkContext.parallelize(data.to_dict(orient='records'))
pairs = rdd.flatMap(lambda row: [(col, row[col]) for col in row.keys()])

print("MAP OUTPUT")

for item in rdd.take(15):
    print(item)

min_values = rdd.reduceByKey(
    lambda a, b: a if a < b else b
)

print("MINIMUM VALUES:")
for parameter, value in min_values.collect():
    print(parameter, ":", value)

max_values = rdd.reduceByKey(
    lambda a, b: a if a > b else b
)

print("MAXIMUM VALUES:")
for parameter, value in max_values.collect():
    print(parameter, ":", value)

import matplotlib.pyplot as plt

for column in data.columns:
    plt.figure(figsize=(8, 4))
    plt.plot(data[column])
    plt.title(f"{column} measurements")
    plt.xlabel("Measurement Number")
    plt.ylabel(column)
    plt.grid(True)
    plt.show()